# Generated by Django 4.2.3 on 2023-07-19 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insulinshot',
            options={'get_latest_by': '-updated_at', 'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='measurement',
            options={'get_latest_by': '-updated_at', 'ordering': ['-updated_at']},
        ),
        migrations.RemoveField(
            model_name='insulinshot',
            name='time',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='insulinshot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insulinshot',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bitessuggestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='insulinshot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_insulin_shots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_measurements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
